services:
  - type: web
    name: nexus-server-bot
    env: python
    plan: free
    build:
      pythonVersion: 3.11.8
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
